
#-->-->-->-->-->-->-->-->-->-->-->-->-->-->-->-->-->-->
# Path of libft.h WITHOUT .h file!  e.g
# LIBFT_PATH = /Users/LIBFT/+libft 	[/libft.h]

PRINTF_PATH_TEST	= /Users/mmensing/Desktop/libft
#/Users/mmensing/Desktop/libft
# :)
#-->-->-->-->-->-->-->-->-->-->-->-->-->-->-->-->-->-->


PRINTF_PATH_MY		= /Users/mmensing/Desktop/libft
NAME				= ft_prinf_tester.a
CC					= gcc
RM					= rm -rf
HEAD				= head.h
FLAGS				= -c -Wall -Werror -Wextra
# for 'test.c' own lib!
EXEC_PRINTF_MY			= -L$(PRINTF_PATH_MY) -lft
EXEC_PRINTF_TEST		= -L$(PRINTF_PATH_TEST) -lft


g:
	@gcc tester.c $(EXEC_PRINT_MY)
	@./a.out
